name: treecrown-detection_detectreeRGB
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - matplotlib
  - urllib3
  - pytorch==1.8.0
  - torchvision==0.9.0
  - tqdm
  - opencv
  - pycurl
  - pip
  - pip:
    - git+https://github.com/alan-turing-institute/scivision.git@add-treecrown-example
    - rasterio
    - detectron2@git+https://github.com/facebookresearch/detectron2.git@v0.6
    - git+https://github.com/ESM-VFC/intake_zenodo_fetcher.git