channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - matplotlib
  - urllib3
  - opencv
  - pytorch==1.8.0
  - torchvision==0.9.0
  - pip
  - pip:
    - scivision
    - detectron2@git+https://github.com/facebookresearch/detectron2.git@v0.6#egg=detectron2
    - git+https://github.com/ESM-VFC/intake_zenodo_fetcher.git